### ISSUE TITLE
Can't read Windows native zip file

### ISSUE THREAD

**Issue by TimG1964** [JuliaIO/ZipArchives.jl#49]
Windows native zip files use a method called Deflated 64. ZipArchive cannot read these files:
```
ERROR: LoadError: ArgumentError: invalid compression method: 9. Only Store and Deflate supported for now
```
It would be good to be able to read Windows native zip files.

**Comment by nhz2** [comment]
Thank you for the issue. Yes, Deflate64 is currently unsupported.

There is no [codec package](https://github.com/JuliaIO/TranscodingStreams.jl?tab=readme-ov-file#codec-packages) that supports Deflate64 right now.

I think [p7zip_jll](https://github.com/JuliaBinaryWrappers/p7zip_jll.jl) supports Deflate64, so maybe there could be an option added to allow `p7zip_jll` to handle the decompression. 7zip is [banned by some organizations](https://discourse.julialang.org/t/alternative-to-7zip-when-installing-packages/111141) it seems, so this would be an optional dependency.

There is also https://github.com/madler/zlib/blob/master/contrib/infback9/infback9.h which could be made into a jll package in [Yggdrasil](https://github.com/JuliaPackaging/Yggdrasil) but this C code is not officially supported it seems. This is the method used by https://github.com/brianhelba/zipfile-deflate64

Another option is to fork https://github.com/GunnarFarneback/Inflate.jl and patch it to work with Deflate64, as I think Deflate and Deflate64 are very similar.

For testing, would you happen to know if there is any good documentation of Deflate64 or any example files to test against?

**Comment by nhz2** [comment]
I found some unofficial documentation in https://libzip.org/specifications/appnote_iz.txt

**Comment by TimG1964** [comment]
This post on discourse seems to suggest that, yes, 7z could help solve this:

https://discourse.julialang.org/t/file-zipping-taking-longer-for-large-files/115963/2?u=timg

**Comment by nhz2** [comment]
I created a WIP package to fix this:
https://discourse.julialang.org/t/ann-codecinflate64-jl-testing-help-needed-from-windows-zip-file-users/117680

**Comment by TimG1964** [comment]
Thank you!
