### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by renatobellotti** [JuliaIO/ZipArchives.jl#60]
When I run the example code from the README, I get the following error message:

```
MethodError: no method matching Union{ZipArchives.ZipFileReader, ZipArchives.ZipBufferReader}(::Vector{UInt8})
```

**Comment by nhz2** [comment]
You are using an older version of ZipArchives. Check out the older readme: https://github.com/JuliaIO/ZipArchives.jl/tree/v1.1.3

**Comment by nhz2** [comment]
Also, what does running:
```julia-repl
julia> import Pkg; Pkg.status()
```
Output?

I'm curious about what other packages may be incompatible with the new version of ZipArchives.
