### ISSUE TITLE
Read only one file in the archive, without loading the data of the others

### ISSUE THREAD

**Issue by fabmazz** [JuliaIO/ZipArchives.jl#79]
Hi,
Very nice library, great alternative to ZipFile!

From the examples posted, I see that you have to read the entire zip archive contents before decompressing it.
I was wondering if it would be possible to implement a way to just read the archive file list, and read one file at a time using a stream-like interface. That way, if I have a rather big zip archive with many files, I can load only the ones that I want, without wasting time and memory for the others.

Thanks a lot!

**Comment by nhz2** [comment]
Thank you for the feedback. Yes this is possible using [`Mmap.jl`](https://docs.julialang.org/en/v1/stdlib/Mmap/) if you are reading a file.

```julia
using Mmap: mmap
using ZipArchives
archive = ZipReader(mmap(open("Downloads/ZipArchives.jl-main.zip")))
zip_openentry(archive, "ZipArchives.jl-main/README.md") do io
    io isa IO
end
```
